# Generated by Django 2.0.7 on 2019-10-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epidemicpred', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='helpno',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
